// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using OrbitAlert.Infrastructure.Persistence;

#nullable disable

namespace OrbitAlert.Infrastructure.Migrations
{
    [DbContext(typeof(OrbitAlertContext))]
    [Migration("20260606155839_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrbitAlert.Domain.Entities.Alerta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_ALERTA")
                        .HasDefaultValueSql("SEQ_ALERTA.NEXTVAL");

                    b.Property<string>("DsObservacao")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("DS_OBSERVACAO");

                    b.Property<DateTime>("DtCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<DateTime?>("DtFechamento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_FECHAMENTO");

                    b.Property<long>("ID_TIPO_ALERTA")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("ID_ZONA")
                        .HasColumnType("NUMBER(19)");

                    b.Property<int>("NrNivelRisco")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NR_NIVEL_RISCO");

                    b.Property<string>("StStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("ST_STATUS");

                    b.HasKey("Id");

                    b.HasIndex("ID_TIPO_ALERTA");

                    b.HasIndex("ID_ZONA");

                    b.ToTable("TB_ALERTA", (string)null);
                });

            modelBuilder.Entity("OrbitAlert.Domain.Entities.AnaliseIa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_ANALISE")
                        .HasDefaultValueSql("SEQ_ANALISE_IA.NEXTVAL");

                    b.Property<string>("DsModeloIa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DS_MODELO_IA");

                    b.Property<string>("DsPrompt")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_PROMPT");

                    b.Property<string>("DsResposta")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_RESPOSTA");

                    b.Property<DateTime>("DtGeracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_GERACAO")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<long>("ID_ALERTA")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("NrTokensUsados")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("NR_TOKENS_USADOS");

                    b.HasKey("Id");

                    b.HasIndex("ID_ALERTA")
                        .IsUnique()
                        .HasDatabaseName("UK_ANALISE_ALERTA");

                    b.ToTable("TB_ANALISE_IA", (string)null);
                });

            modelBuilder.Entity("OrbitAlert.Domain.Entities.EstacaoIot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_ESTACAO")
                        .HasDefaultValueSql("SEQ_ESTACAO_IOT.NEXTVAL");

                    b.Property<string>("DsLocalizacao")
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)")
                        .HasColumnName("DS_LOCALIZACAO");

                    b.Property<DateTime>("DtInstalacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_INSTALACAO")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<long>("ID_ZONA")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("NmEstacao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NM_ESTACAO");

                    b.Property<string>("StAtivo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("ST_ATIVO");

                    b.HasKey("Id");

                    b.HasIndex("ID_ZONA");

                    b.ToTable("TB_ESTACAO_IOT", (string)null);
                });

            modelBuilder.Entity("OrbitAlert.Domain.Entities.HistoricoAlerta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_HISTORICO")
                        .HasDefaultValueSql("SEQ_HISTORICO_ALERTA.NEXTVAL");

                    b.Property<string>("DsObservacao")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_OBSERVACAO");

                    b.Property<DateTime>("DtAlteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ALTERACAO")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<long>("ID_ALERTA")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("NmUsuarioMod")
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NM_USUARIO_MOD");

                    b.Property<int?>("NrIndiceRisco")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NR_INDICE_RISCO");

                    b.Property<string>("StStatusAnt")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("ST_STATUS_ANT");

                    b.Property<string>("StStatusNovo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("ST_STATUS_NOVO");

                    b.HasKey("Id");

                    b.HasIndex("ID_ALERTA");

                    b.ToTable("TB_HISTORICO_ALERTA", (string)null);
                });

            modelBuilder.Entity("OrbitAlert.Domain.Entities.LeituraIot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_LEITURA")
                        .HasDefaultValueSql("SEQ_LEITURA_IOT.NEXTVAL");

                    b.Property<DateTime>("DtLeitura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_LEITURA")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<long>("ID_ESTACAO")
                        .HasColumnType("NUMBER(19)");

                    b.Property<decimal>("NrChuvaMm")
                        .HasColumnType("NUMBER(6,2)")
                        .HasColumnName("NR_CHUVA_MM");

                    b.Property<int>("NrIndiceRisco")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NR_INDICE_RISCO");

                    b.Property<decimal>("NrTemperatura")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("NR_TEMPERATURA");

                    b.Property<decimal>("NrUmidade")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("NR_UMIDADE");

                    b.HasKey("Id");

                    b.HasIndex("ID_ESTACAO");

                    b.ToTable("TB_LEITURA_IOT", (string)null);
                });

            modelBuilder.Entity("OrbitAlert.Domain.Entities.Municipio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_MUNICIPIO")
                        .HasDefaultValueSql("SEQ_MUNICIPIO.NEXTVAL");

                    b.Property<DateTime>("DtCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CADASTRO")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<string>("NmEstado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_ESTADO");

                    b.Property<string>("NmMunicipio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NM_MUNICIPIO");

                    b.Property<decimal>("NrLatitude")
                        .HasColumnType("NUMBER(10,7)")
                        .HasColumnName("NR_LATITUDE");

                    b.Property<decimal>("NrLongitude")
                        .HasColumnType("NUMBER(10,7)")
                        .HasColumnName("NR_LONGITUDE");

                    b.Property<long?>("NrPopulacao")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("NR_POPULACAO");

                    b.Property<string>("StAtivo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("ST_ATIVO");

                    b.HasKey("Id");

                    b.ToTable("TB_MUNICIPIO", (string)null);
                });

            modelBuilder.Entity("OrbitAlert.Domain.Entities.Notificacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_NOTIFICACAO")
                        .HasDefaultValueSql("SEQ_NOTIFICACAO.NEXTVAL");

                    b.Property<string>("DsMensagem")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_MENSAGEM");

                    b.Property<string>("DsTitulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("DS_TITULO");

                    b.Property<DateTime>("DtEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ENVIO")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<long>("ID_ALERTA")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("ID_USUARIO")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("StLida")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("ST_LIDA");

                    b.Property<string>("TpNotificacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TP_NOTIFICACAO");

                    b.HasKey("Id");

                    b.HasIndex("ID_ALERTA");

                    b.HasIndex("ID_USUARIO");

                    b.ToTable("TB_NOTIFICACAO", (string)null);
                });

            modelBuilder.Entity("OrbitAlert.Domain.Entities.TipoAlerta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_TIPO_ALERTA")
                        .HasDefaultValueSql("SEQ_TIPO_ALERTA.NEXTVAL");

                    b.Property<string>("DsDescricao")
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)")
                        .HasColumnName("DS_DESCRICAO");

                    b.Property<string>("NmTipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NM_TIPO");

                    b.HasKey("Id");

                    b.HasIndex("NmTipo")
                        .IsUnique()
                        .HasDatabaseName("UK_TIPO_ALERTA_NOME");

                    b.ToTable("TB_TIPO_ALERTA", (string)null);
                });

            modelBuilder.Entity("OrbitAlert.Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_USUARIO")
                        .HasDefaultValueSql("SEQ_USUARIO.NEXTVAL");

                    b.Property<string>("DsEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("DS_EMAIL");

                    b.Property<string>("DsSenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_SENHA_HASH");

                    b.Property<DateTime>("DtCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CADASTRO")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<string>("NmUsuario")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NM_USUARIO");

                    b.Property<string>("StAtivo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("ST_ATIVO");

                    b.Property<string>("TpPerfil")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("TP_PERFIL");

                    b.HasKey("Id");

                    b.HasIndex("DsEmail")
                        .IsUnique()
                        .HasDatabaseName("TB_USUARIO_EMAIL_UN");

                    b.ToTable("TB_USUARIO", (string)null);
                });

            modelBuilder.Entity("OrbitAlert.Domain.Entities.UsuarioMunicipio", b =>
                {
                    b.Property<long>("IdUsuario")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<long>("IdMunicipio")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_MUNICIPIO");

                    b.Property<DateTime>("DtVinculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_VINCULO")
                        .HasDefaultValueSql("SYSDATE");

                    b.HasKey("IdUsuario", "IdMunicipio");

                    b.HasIndex("IdMunicipio");

                    b.ToTable("TB_USUARIO_MUNICIPIO", (string)null);
                });

            modelBuilder.Entity("OrbitAlert.Domain.Entities.ZonaRisco", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_ZONA")
                        .HasDefaultValueSql("SEQ_ZONA_RISCO.NEXTVAL");

                    b.Property<string>("DsDescricao")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_DESCRICAO");

                    b.Property<DateTime>("DtCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CADASTRO")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<long>("ID_MUNICIPIO")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("NmZona")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NM_ZONA");

                    b.Property<decimal>("NrLatitude")
                        .HasColumnType("NUMBER(10,7)")
                        .HasColumnName("NR_LATITUDE");

                    b.Property<int>("NrLimiarAlerta")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NR_LIMIAR_ALERTA");

                    b.Property<decimal>("NrLongitude")
                        .HasColumnType("NUMBER(10,7)")
                        .HasColumnName("NR_LONGITUDE");

                    b.Property<string>("StAtivo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("ST_ATIVO");

                    b.HasKey("Id");

                    b.HasIndex("ID_MUNICIPIO");

                    b.ToTable("TB_ZONA_RISCO", (string)null);
                });

            modelBuilder.Entity("OrbitAlert.Domain.Entities.Alerta", b =>
                {
                    b.HasOne("OrbitAlert.Domain.Entities.TipoAlerta", "TipoAlerta")
                        .WithMany("Alertas")
                        .HasForeignKey("ID_TIPO_ALERTA")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrbitAlert.Domain.Entities.ZonaRisco", "ZonaRisco")
                        .WithMany("Alertas")
                        .HasForeignKey("ID_ZONA")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoAlerta");

                    b.Navigation("ZonaRisco");
                });

            modelBuilder.Entity("OrbitAlert.Domain.Entities.AnaliseIa", b =>
                {
                    b.HasOne("OrbitAlert.Domain.Entities.Alerta", "Alerta")
                        .WithOne("AnaliseIa")
                        .HasForeignKey("OrbitAlert.Domain.Entities.AnaliseIa", "ID_ALERTA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alerta");
                });

            modelBuilder.Entity("OrbitAlert.Domain.Entities.EstacaoIot", b =>
                {
                    b.HasOne("OrbitAlert.Domain.Entities.ZonaRisco", "ZonaRisco")
                        .WithMany("Estacoes")
                        .HasForeignKey("ID_ZONA")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ZonaRisco");
                });

            modelBuilder.Entity("OrbitAlert.Domain.Entities.HistoricoAlerta", b =>
                {
                    b.HasOne("OrbitAlert.Domain.Entities.Alerta", "Alerta")
                        .WithMany("Historicos")
                        .HasForeignKey("ID_ALERTA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alerta");
                });

            modelBuilder.Entity("OrbitAlert.Domain.Entities.LeituraIot", b =>
                {
                    b.HasOne("OrbitAlert.Domain.Entities.EstacaoIot", "EstacaoIot")
                        .WithMany("Leituras")
                        .HasForeignKey("ID_ESTACAO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstacaoIot");
                });

            modelBuilder.Entity("OrbitAlert.Domain.Entities.Notificacao", b =>
                {
                    b.HasOne("OrbitAlert.Domain.Entities.Alerta", "Alerta")
                        .WithMany("Notificacoes")
                        .HasForeignKey("ID_ALERTA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrbitAlert.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Notificacoes")
                        .HasForeignKey("ID_USUARIO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alerta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("OrbitAlert.Domain.Entities.UsuarioMunicipio", b =>
                {
                    b.HasOne("OrbitAlert.Domain.Entities.Municipio", "Municipio")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdMunicipio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrbitAlert.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Municipios")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Municipio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("OrbitAlert.Domain.Entities.ZonaRisco", b =>
                {
                    b.HasOne("OrbitAlert.Domain.Entities.Municipio", "Municipio")
                        .WithMany("Zonas")
                        .HasForeignKey("ID_MUNICIPIO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("OrbitAlert.Domain.Entities.Alerta", b =>
                {
                    b.Navigation("AnaliseIa");

                    b.Navigation("Historicos");

                    b.Navigation("Notificacoes");
                });

            modelBuilder.Entity("OrbitAlert.Domain.Entities.EstacaoIot", b =>
                {
                    b.Navigation("Leituras");
                });

            modelBuilder.Entity("OrbitAlert.Domain.Entities.Municipio", b =>
                {
                    b.Navigation("Usuarios");

                    b.Navigation("Zonas");
                });

            modelBuilder.Entity("OrbitAlert.Domain.Entities.TipoAlerta", b =>
                {
                    b.Navigation("Alertas");
                });

            modelBuilder.Entity("OrbitAlert.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Municipios");

                    b.Navigation("Notificacoes");
                });

            modelBuilder.Entity("OrbitAlert.Domain.Entities.ZonaRisco", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Estacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
